In [75]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
#from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score
from sklearn import tree

# Golf Play example 

In [423]:
df=pd.read_excel('C:\\Users\Admin\Desktop\Data_Science\L&D\R\R_archive\DT_Golf.xlsx')


In [430]:
df.columns

Index(['Outlook', 'Temp', 'Humidity', 'Windy ', 'Play Golf'], dtype='object')

In [460]:
#df['Windy ']=df['Windy '].str.strip()
df_1=pd.get_dummies(df)


In [439]:
X=df_1.iloc[:,:10]
Y=df_1.iloc[:,10:12]
yy=df[['Play Golf']]


In [446]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=100)


In [465]:
#X_train,X_test,yy_train,yy_test=train_test_split(X,yy,test_size=0.2,random_state=100)


## Build the DT model

In [533]:
Y

Play Golf_No  Play Golf_Yes
0              1              0
1              1              0
2              0              1
3              0              1
4              0              1
5              1              0
6              0              1
7              1              0
8              0              1
9              0              1
10             0              1
11             0              1
12             0              1
13             1              0

In [534]:
df_model=DecisionTreeClassifier()
df_model.fit(X,Y)


print(df_model.predict(X_test))
#print(X_test)
print(Y_test)

[[0. 1.]
 [0. 1.]
 [1. 0.]]
    Play Golf_No  Play Golf_Yes
11             0              1
12             0              1
5              1              0


In [470]:
df_model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

## Let's build using Entropy method

In [539]:
df_model

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [536]:
df_model=DecisionTreeClassifier(criterion='entropy')
df_model.fit(X,Y)


print(df_model.predict(X_test))
#print(X_test)
print(Y_test)

[[0. 1.]
 [0. 1.]
 [1. 0.]]
    Play Golf_No  Play Golf_Yes
11             0              1
12             0              1
5              1              0


## What will happen if Y(target) in model is categorical ?

__*Try with Y without encoding*__

In [473]:
df_model=DecisionTreeClassifier()
#df_model.fit(X,yy)


#print(df_model.predict(X_test))
#print(X_test)
#print(Y_test)

In [474]:
df_model=DecisionTreeClassifier()
#df_model.fit(X,yy)


#print(df_model.predict(X_train))
#print(X_test)
#print(Y_train)

dot_data = tree.export_graphviz(df_model, out_file=None, 
#feature_names=['Outlook', 'Temp', 'Humidity', 'Windy'],
feature_names=X.columns,                                
class_names='Play Golf',  
filled=True, rounded=True,  
special_characters=True)  
graph = graphviz.Source(dot_data)  
graph

## Confusion matrix

In [508]:
from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(yy_test, df_model.predict(X_test)))
print(classification_report(yy_test, df_model.predict(X_test)))

[[1 0]
 [0 2]]
              precision    recall  f1-score   support

          No       1.00      1.00      1.00         1
         Yes       1.00      1.00      1.00         2

   micro avg       1.00      1.00      1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



from sklearn.metrics import roc_auc_score,roc_curve

DT_roc_auc = roc_auc_score(Y_test, df_model.predict(X_test))
#fpr, tpr, thresholds = roc_curve(yy_test, df_model.predict_proba(X_test)[:,1])
DT_roc_auc